name: Pull feeds daily

on:
  # lets you run it manually from the Actions tab
  workflow_dispatch:
  # runs every day at 09:05 NZ time (20:05 UTC)
  schedule:
    - cron: "5 20 * * *"

permissions:
  contents: write  # allow the workflow to commit/push changes

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Pull feeds
        run: npm run pull:feeds

      - name: Commit updates
        run: |
          if git diff --quiet -- public/; then
            echo "No public changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/feeds.json public/ingestion.json
          git commit -m "chore(ci): update feeds.json [skip ci]" || exit 0
          git push
